Publish swiper 스와이퍼
MARS-crew/mars pull request #30
Opened 2022-06-24 16:04 UTC by jew2222

**작업 내용**
스와이퍼 사용한 html 과 js 구조 잡기 작업 

index.html 
swiper.js
main.css

2022-06-25 02:41 UTC, mokhs00 commented
@jew2222 main 브랜치 변경사항이 병합되지 않은 것 같아요 main 브랜치 -> publish-swiper 브랜치로 병합 한 번 해주세요~

2022-06-25 03:29 UTC, mokhs00 requested changes
main 브랜치 변경사항이 병합되지 않은 것 같아요 main 브랜치 -> publish-swiper 브랜치로 병합 한 번 해주세요~ 
RC 걸어두겠습니다 변경 후에 우측 상단 reviewer에서 새로고침?모양 버튼 눌러서 re-request 보내주세요!

2022-06-27 09:47 UTC, jew2222 commented
네 알겠습니다! 이전 브랜치 커밋에서 수정해야 할 부분을 발견해서 새로 브랜치를 만들고 병합하겠습니다

2022-06-27 09:50 UTC, mokhs00 commented
@jew2222 다른 브랜치에서 작업할 예정이라면 해당 PR close 부탁드려요!

2022-06-27 10:58 UTC, closed without merging